# Generated by Django 4.2.5 on 2024-02-17 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('max_price', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('image_url', models.CharField(default='https://media.istockphoto.com/id/155009909/photo/beautiful-smiling-cute-baby.jpg?s=612x612&w=0&k=20&c=-XRwxMdtne8UiFqJC3_k0kW4dsnJXR1tAPxu5dm63lU=', max_length=555)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
